# Generated by Django 5.0 on 2023-12-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
